version: '3.8'

services:
  angular-app:
    image: kafkaetech/kcm-manager-ui:0.0.3
    volumes:
      - ./runtime-config.json:/usr/share/nginx/html/runtime-config.json
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"

  kcm-manager-api:
    image: kafkaetech/kcm-manager:0.60
    environment:
      - KCM_DB_URL=jdbc:mysql://kcm-manager-db:3306/kcm_db
      - KCM_DB_USER=kcm_user
      - KCM_DB_PWD=kcm_password
      - KCM_REDIS_DB_HOST=redis
      - KCM_REDIS_DB_PORT=6379
      - KCM_REDIS_DB_PASSWORD=
      - KCM_REDIS_DB_NAME=0
    ports:
      - "8080:8080"
    depends_on:
      - kcm-manager-db
      - redis

  kcm-manager-db:
    image: mysql:8.0.38
    command: [ 'mysqld','--character-set-server=utf8','--default-authentication-plugin=mysql_native_password' ]
    restart: on-failure
    environment:
      MYSQL_ROOT_PASSWORD: 'sql_password'
      MYSQL_DATABASE: kcm_db
      MYSQL_USER: kcm_user
      MYSQL_PASSWORD: 'kcm_password'
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql
  pma:
    image: phpmyadmin/phpmyadmin:5.2.1
    restart: on-failure
    depends_on:
      - kcm-manager-db
    environment:
      PMA_HOSTS: kcm-manager-db
    ports:
      - "7777:80"
    
  redis:
    image: redis:6.2
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: ["redis-server", "--save", "60", "1", "--loglevel", "notice"]

volumes:
  redis_data:
  dbdata:
