version: '3.8'

services:
  angular-app:
    image: kafkaetech/kcm-manager-ui:latest
    volumes:
      - ./runtime-config.json:/usr/share/nginx/html/runtime-config.json
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"

  kcm-manager-api:
    image: kafkaetech/kcm-manager:latest
    environment:
      - KCM_DB_URL=jdbc:mysql://kcm-manager-db:3306/kcm_db
      - KCM_DB_USER=kcm_user
      - KCM_DB_PWD=kcm_password
      - KCM_REDIS_DB_HOST=redis
      - KCM_REDIS_DB_PORT=6379
      - KCM_REDIS_DB_PASSWORD=
      - KCM_REDIS_DB_NAME=0
      - KCM_APP_FILES_PATH=/app/files
      - KCM_JWT_PRIVATE_KEY=/app/jwt/private.pem
      - KCM_JWT_PUBLIC_KEY=/app/jwt/public.pem
    volumes:
      - kcmdata:/app/files
      - ./jwt:/app/jwt
    ports:
      - "8080:8080"
    depends_on:
      - kcm-manager-db
      - redis

  kcm-manager-db:
    image: mysql:8.0.38
    command: [ 'mysqld','--character-set-server=utf8','--default-authentication-plugin=mysql_native_password' ]
    restart: on-failure
    environment:
      MYSQL_ROOT_PASSWORD: 'sql_password'
      MYSQL_DATABASE: kcm_db
      MYSQL_USER: kcm_user
      MYSQL_PASSWORD: 'kcm_password'
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql
  pma:
    image: phpmyadmin/phpmyadmin:5.2.1
    restart: on-failure
    depends_on:
      - kcm-manager-db
    environment:
      PMA_HOSTS: kcm-manager-db
    ports:
      - "7777:80"

  redis:
    image: redis:6.2
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: ["redis-server", "--save", "60", "1", "--loglevel", "notice"]


  controller-1:
    image: apache/kafka:latest
    container_name: controller-1
    ports:
      - 19093:9093
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: controller
      KAFKA_LISTENERS: CONTROLLER://:9093
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@controller-1:9093,2@controller-2:9093,3@controller-3:9093
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_LOG_DIRS: "/var/lib/kafka/data"
    volumes:
      - controller1-data:/var/lib/kafka/data

  controller-2:
    image: apache/kafka:latest
    container_name: controller-2
    ports:
      - 29093:9093
    environment:
      KAFKA_NODE_ID: 2
      KAFKA_PROCESS_ROLES: controller
      KAFKA_LISTENERS: CONTROLLER://:9093
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@controller-1:9093,2@controller-2:9093,3@controller-3:9093
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_LOG_DIRS: "/var/lib/kafka/data"
    volumes:
      - controller2-data:/var/lib/kafka/data

  controller-3:
    image: apache/kafka:latest
    container_name: controller-3
    ports:
      - 39093:9093
    environment:
      KAFKA_NODE_ID: 3
      KAFKA_PROCESS_ROLES: controller
      KAFKA_LISTENERS: CONTROLLER://:9093
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@controller-1:9093,2@controller-2:9093,3@controller-3:9093
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_LOG_DIRS: "/var/lib/kafka/data"
    volumes:
      - controller3-data:/var/lib/kafka/data

  broker-1:
    image: apache/kafka:latest
    container_name: broker-1
    ports:
      - "9492:9492"  # PLAINTEXT_HOST
      - "9493:9493"  # SASL_SSL_HOST
    environment:
      KAFKA_NODE_ID: 4
      KAFKA_LOG_DIRS: "/var/lib/kafka/data"
      KAFKA_PROCESS_ROLES: broker
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@controller-1:9093,2@controller-2:9093,3@controller-3:9093
      KAFKA_LISTENERS: PLAINTEXT_INTERNAL://:9092,PLAINTEXT_HOST://:9492,SASL_SSL_INTERNAL://:9093,SASL_SSL_HOST://:9493
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT_INTERNAL://broker-1:9092,PLAINTEXT_HOST://localhost:9492,SASL_SSL_INTERNAL://broker-1:9093,SASL_SSL_HOST://localhost:9493
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT,SASL_SSL_INTERNAL:SASL_SSL,SASL_SSL_HOST:SASL_SSL
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT_INTERNAL
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_SASL_MECHANISM_INTER_BROKER_PROTOCOL: SCRAM-SHA-512
      KAFKA_SASL_ENABLED_MECHANISMS: SCRAM-SHA-512
      KAFKA_SSL_KEYSTORE_LOCATION: /var/private/ssl/kafka.keystore.jks
      KAFKA_SSL_KEYSTORE_PASSWORD: changeit
      KAFKA_SSL_TRUSTSTORE_LOCATION: /var/private/ssl/kafka.truststore.jks
      KAFKA_SSL_TRUSTSTORE_PASSWORD: changeit
      KAFKA_OPTS: "-Djava.security.auth.login.config=/etc/kafka/jaas.conf"
    volumes:
      - broker1-data:/var/lib/kafka/data
      - ./new_ssl/broker-1:/var/private/ssl
      - ./jaas.conf:/etc/kafka/jaas.conf
    depends_on:
      - controller-1
      - controller-2
      - controller-3

  broker-2:
    image: apache/kafka:latest
    container_name: broker-2
    ports:
      - "9592:9592"  # PLAINTEXT_HOST
      - "9593:9593"  # SASL_SSL_HOST
    environment:
      KAFKA_NODE_ID: 5
      KAFKA_LOG_DIRS: "/var/lib/kafka/data"
      KAFKA_PROCESS_ROLES: broker
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@controller-1:9093,2@controller-2:9093,3@controller-3:9093
      KAFKA_LISTENERS: PLAINTEXT_INTERNAL://:9092,PLAINTEXT_HOST://:9592,SASL_SSL_INTERNAL://:9093,SASL_SSL_HOST://:9593
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT_INTERNAL://broker-2:9092,PLAINTEXT_HOST://localhost:9592,SASL_SSL_INTERNAL://broker-2:9093,SASL_SSL_HOST://localhost:9593
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT,SASL_SSL_INTERNAL:SASL_SSL,SASL_SSL_HOST:SASL_SSL
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT_INTERNAL
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_SASL_MECHANISM_INTER_BROKER_PROTOCOL: SCRAM-SHA-512
      KAFKA_SASL_ENABLED_MECHANISMS: SCRAM-SHA-512
      KAFKA_SSL_KEYSTORE_LOCATION: /var/private/ssl/kafka.keystore.jks
      KAFKA_SSL_KEYSTORE_PASSWORD: changeit
      KAFKA_SSL_TRUSTSTORE_LOCATION: /var/private/ssl/kafka.truststore.jks
      KAFKA_SSL_TRUSTSTORE_PASSWORD: changeit
      KAFKA_OPTS: "-Djava.security.auth.login.config=/etc/kafka/jaas.conf"
    volumes:
      - broker2-data:/var/lib/kafka/data
      - ./new_ssl/broker-2:/var/private/ssl
      - ./jaas.conf:/etc/kafka/jaas.conf
    depends_on:
      - controller-1
      - controller-2
      - controller-3

  broker-3:
    image: apache/kafka:latest
    container_name: broker-3
    ports:
      - "9692:9692"  # PLAINTEXT_HOST
      - "9693:9693"  # SASL_SSL_HOST
    environment:
      KAFKA_NODE_ID: 6
      KAFKA_LOG_DIRS: "/var/lib/kafka/data"
      KAFKA_PROCESS_ROLES: broker
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@controller-1:9093,2@controller-2:9093,3@controller-3:9093
      KAFKA_LISTENERS: PLAINTEXT_INTERNAL://:9092,PLAINTEXT_HOST://:9692,SASL_SSL_INTERNAL://:9093,SASL_SSL_HOST://:9693
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT_INTERNAL://broker-3:9092,PLAINTEXT_HOST://localhost:9692,SASL_SSL_INTERNAL://broker-3:9093,SASL_SSL_HOST://localhost:9693
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT,SASL_SSL_INTERNAL:SASL_SSL,SASL_SSL_HOST:SASL_SSL
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT_INTERNAL
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_SASL_MECHANISM_INTER_BROKER_PROTOCOL: SCRAM-SHA-512
      KAFKA_SASL_ENABLED_MECHANISMS: SCRAM-SHA-512
      KAFKA_SSL_KEYSTORE_LOCATION: /var/private/ssl/kafka.keystore.jks
      KAFKA_SSL_KEYSTORE_PASSWORD: changeit
      KAFKA_SSL_TRUSTSTORE_LOCATION: /var/private/ssl/kafka.truststore.jks
      KAFKA_SSL_TRUSTSTORE_PASSWORD: changeit
      KAFKA_OPTS: "-Djava.security.auth.login.config=/etc/kafka/jaas.conf"
    volumes:
      - broker3-data:/var/lib/kafka/data
      - ./new_ssl/broker-3:/var/private/ssl
      - ./jaas.conf:/etc/kafka/jaas.conf
    depends_on:
      - controller-1
      - controller-2
      - controller-3

  kafka-connect:
    image: confluentinc/cp-kafka-connect:6.2.0
    container_name: kafka-connect
    ports:
      - 8083:8083
    environment:
      CONNECT_BOOTSTRAP_SERVERS: broker-1:9092,broker-2:9092,broker-3:9092
      CONNECT_REST_PORT: 8083
      CONNECT_GROUP_ID: kafka-connect-group
      CONNECT_CONFIG_STORAGE_TOPIC: connect-configs
      CONNECT_OFFSET_STORAGE_TOPIC: connect-offsets
      CONNECT_STATUS_STORAGE_TOPIC: connect-status
      CONNECT_KEY_CONVERTER: org.apache.kafka.connect.json.JsonConverter
      CONNECT_VALUE_CONVERTER: org.apache.kafka.connect.json.JsonConverter
      CONNECT_REST_ADVERTISED_HOST_NAME: kafka-connect
      CONNECT_PLUGIN_PATH: /usr/share/java
      CONNECT_REST_EXTENSION_CLASSES: org.apache.kafka.connect.rest.basic.auth.extension.BasicAuthSecurityRestExtension
      #CONNECT_BASIC_AUTH_CREDENTIALS_SOURCE: STATIC
      #CONNECT_BASIC_AUTH_USERS: admin:password
      KAFKA_OPTS: "-Djava.security.auth.login.config=/kafka/config/basic-auth/jaas.config"
    volumes:
        - ./kafka_connect_jaas.config:/kafka/config/basic-auth/jaas.config
        - ./connect.password:/kafka/config/basic-auth/connect.password
    depends_on:
      - broker-1
      - broker-2
      - broker-3

volumes:
  redis_data:
  dbdata:
  kcmdata:
  controller1-data:
  controller2-data:
  controller3-data:
  broker1-data:
  broker2-data:
  broker3-data: